/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as KbRouteImport } from './routes/kb'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as KbIndexRouteImport } from './routes/kb.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as SpecsIdRouteImport } from './routes/specs.$id'
import { Route as KbIdRouteImport } from './routes/kb.$id'
import { Route as DocsUserGuideRouteImport } from './routes/docs.user-guide'
import { Route as DocsTutorialRouteImport } from './routes/docs.tutorial'
import { Route as DocsReferenceRouteImport } from './routes/docs.reference'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRoute = KbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecsRoute,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KbRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const SpecsIdRoute = SpecsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecsRoute,
} as any)
const KbIdRoute = KbIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KbRoute,
} as any)
const DocsUserGuideRoute = DocsUserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialRoute = DocsTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferenceRoute = DocsReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/kb': typeof KbRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/specs': typeof SpecsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/user-guide': typeof DocsUserGuideRoute
  '/kb/$id': typeof KbIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/docs/': typeof DocsIndexRoute
  '/kb/': typeof KbIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/user-guide': typeof DocsUserGuideRoute
  '/kb/$id': typeof KbIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/docs': typeof DocsIndexRoute
  '/kb': typeof KbIndexRoute
  '/specs': typeof SpecsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/kb': typeof KbRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/specs': typeof SpecsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/user-guide': typeof DocsUserGuideRoute
  '/kb/$id': typeof KbIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/docs/': typeof DocsIndexRoute
  '/kb/': typeof KbIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/kb'
    | '/search'
    | '/settings'
    | '/specs'
    | '/tasks'
    | '/welcome'
    | '/docs/reference'
    | '/docs/tutorial'
    | '/docs/user-guide'
    | '/kb/$id'
    | '/specs/$id'
    | '/tasks/$id'
    | '/docs/'
    | '/kb/'
    | '/specs/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/docs/reference'
    | '/docs/tutorial'
    | '/docs/user-guide'
    | '/kb/$id'
    | '/specs/$id'
    | '/tasks/$id'
    | '/docs'
    | '/kb'
    | '/specs'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/kb'
    | '/search'
    | '/settings'
    | '/specs'
    | '/tasks'
    | '/welcome'
    | '/docs/reference'
    | '/docs/tutorial'
    | '/docs/user-guide'
    | '/kb/$id'
    | '/specs/$id'
    | '/tasks/$id'
    | '/docs/'
    | '/kb/'
    | '/specs/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  KbRoute: typeof KbRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SpecsRoute: typeof SpecsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/specs/': {
      id: '/specs/'
      path: '/'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/kb/': {
      id: '/kb/'
      path: '/'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof KbRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/specs/$id': {
      id: '/specs/$id'
      path: '/$id'
      fullPath: '/specs/$id'
      preLoaderRoute: typeof SpecsIdRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/kb/$id': {
      id: '/kb/$id'
      path: '/$id'
      fullPath: '/kb/$id'
      preLoaderRoute: typeof KbIdRouteImport
      parentRoute: typeof KbRoute
    }
    '/docs/user-guide': {
      id: '/docs/user-guide'
      path: '/user-guide'
      fullPath: '/docs/user-guide'
      preLoaderRoute: typeof DocsUserGuideRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial': {
      id: '/docs/tutorial'
      path: '/tutorial'
      fullPath: '/docs/tutorial'
      preLoaderRoute: typeof DocsTutorialRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reference': {
      id: '/docs/reference'
      path: '/reference'
      fullPath: '/docs/reference'
      preLoaderRoute: typeof DocsReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsReferenceRoute: typeof DocsReferenceRoute
  DocsTutorialRoute: typeof DocsTutorialRoute
  DocsUserGuideRoute: typeof DocsUserGuideRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsReferenceRoute: DocsReferenceRoute,
  DocsTutorialRoute: DocsTutorialRoute,
  DocsUserGuideRoute: DocsUserGuideRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface KbRouteChildren {
  KbIdRoute: typeof KbIdRoute
  KbIndexRoute: typeof KbIndexRoute
}

const KbRouteChildren: KbRouteChildren = {
  KbIdRoute: KbIdRoute,
  KbIndexRoute: KbIndexRoute,
}

const KbRouteWithChildren = KbRoute._addFileChildren(KbRouteChildren)

interface SpecsRouteChildren {
  SpecsIdRoute: typeof SpecsIdRoute
  SpecsIndexRoute: typeof SpecsIndexRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsIdRoute: SpecsIdRoute,
  SpecsIndexRoute: SpecsIndexRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  KbRoute: KbRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SpecsRoute: SpecsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
